exports.projects = [
  /*{
    color: '#4C2998',
    title: 'Pixel Legion',
    duration: 'Oct 2019 - Present',
    position: 'Full Stack Web Engineer',
    type: 'web',
    src: require('../../images/timetracker.png'),
    url: '/projects/pixel-legion',
    freelance: true,
    id: 'legion',
  },*/
  /*{
    color: '',
    title: 'Nkowa okwu | Igbo API',
    duration: 'Sept 2020 - Present',
    position: 'Creator | Full Stack Engineer',
    type: 'web',
    src: require('../../images/nkowaokwu.png'),
    url: '/projects/igbo-api',
    freelance: false,
    id: 'igbo-api',
  },*/
  {
    color: '#357BCD',
    title: 'Timetracker',
    duration: 'Jun 2019 - Jan 2020',
    position: 'Full Stack Mobile Engineer',
    type: 'mobile',
    src: require('../../images/timetracker.png'),
    url: '/projects/timetracker',
    freelance: false,
    id: 'timetracker',
  },
  {
    color: '#2C3E50',
    title: 'College Pulse',
    duration: 'Sept 2017 - Jun 2018',
    position: 'Full Stack Web Engineer',
    type: 'web',
    src: require('../../images/pulse.png'),
    url: '/projects/college-pulse',
    freelance: true,
    id: 'pulse',
  },
  {
    color: '#430303',
    title: 'Hamono',
    duration: 'Nov 2017 - Jan 2018',
    position: 'Game Developer',
    type: 'game',
    src: require('../../images/hamono.png'),
    url: '/projects/hamono',
    freelance: false,
    id: 'hamono',
  },
]
