name: Publish Personal Site

on:
  push:
    branches:
      - dev
  schedule:
    # Runs every Friday at 3:00 PM PST
    - cron: '0 11 * * 5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.DEPLOY_PERSONAL_SITE }}
          deploy-branch: master

